[ids]
*

[main]
# Maps capslock to escape when pressed and layer(num) when held.
capslock = layer(mod)
control = numlock

# Unmap some of these function keys because I keep accidentally pressing them on
# the new keyboard.
pageup = backspace
pagedown = esc
home = esc
end = esc

# Unbind backspace to force myself to learn the new keybind c-h
# backspace = layer(num)

[control]
capslock = capslock
h = backspace
1 = (
2 = {
3 = [
8 = ]
9 = }
0 = )

[mod:C]
n = down
p = up
h = backspace
j = enter

1 = (
2 = {
3 = [
8 = ]
9 = }
0 = )
