# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
 
[character] 
success_symbol = '[❯](bold blue)' 

[package]
disabled = true

[line_break]
disabled = true

[directory]
truncation_length = 1
truncation_symbol = ' /'
style = 'bold blue'

[git_status]
style = 'bold blue'

# Language Specific Settings
[python]
disabled = true

[rust]
disabled = true
