# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
 
[character] 
success_symbol = '[❯](bold purple)' 

[package]
disabled = true

[line_break]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 1
truncation_symbol = ' ⟶ '
style = 'bold blue'

[git_status]
style = 'bold blue'

# Language Specific Settings
[python]
disabled = false
symbol = ' '

[rust]
disabled = false
symbol = ' '

[haskell]
disabled = false
symbol = ' '

[julia]
disabled = false
symbol = ' '

[c]
disabled = false
symbol = 'C '
style = 'bold cyan'

[golang]
disabled = false
symbol = ' '

[lua]
disabled = false
symbol = ' '

[rlang]
disabled = false
symbol = 'R '
