# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '[ → ](bold blue)$all'

[character] 
success_symbol = '[✗](bold purple)' 
error_symbol = '[✗](bold red)' 

[package]
disabled = true

[line_break]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncation_length = 1
style = 'bold blue'

[git_status]
style = 'bold blue'

# Language Specific Settings
[python]
disabled = false
symbol = ' '

[rust]
disabled = false
symbol = ' '

[haskell]
disabled = false
symbol = ' '

[julia]
disabled = false
symbol = ' '

[c]
disabled = false
symbol = ' '
style = 'bold cyan'

[golang]
disabled = false
symbol = ' '

[lua]
disabled = false
symbol = ' '

[rlang]
symbol = ' '
disabled = false

[php]
symbol = ' '
disabled = false

[ruby]
symbol = ' '
disabled = false

[zig]
symbol = ' '
disabled = false
