#!/usr/bin/env bash


options=$(echo "open kill-session rename-session" | tr ' ' '\n')
selected=$(tmux list-sessions | awk '{print $1}' | sed "s/://" | fzf)

if [[ -z $selected ]]; then
	exit 0
else
	selected_option=$(printf "$options" | fzf)
fi

if [[ $selected_option == "open" ]]; then
	tmux switch-client -t $selected
elif [[ $selected_option == "kill-session" ]]; then
	tmux kill-session -t $selected
elif [[ $selected_option == "rename-session" ]]; then
	read -p "Enter new name: " new_session_name
	tmux rename-session -t $selected $new_session_name
else
	exit 0
fi
