#!/usr/bin/bash

echo "Total: $(task status:pending count)\
 / Pending: $(task +READY count)\
 / Scheduled: $(task count +SCHEDULED)\
 / Blocked: $(task count +BLOCKED)"
task list +READY && while true; do sleep 1; done
